apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "twenty.fullname" . }}
  labels:
    {{- include "twenty.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "twenty.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: server
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "twenty.labels" . | nindent 8 }}
        app.kubernetes.io/component: server
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "twenty.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if or .Values.twenty.envFromConfigMapName .Values.twenty.envFromSecretName -}}
          envFrom:
            {{- if .Values.twenty.envFromConfigMapName }}
            - configMapRef:
                name: {{ .Values.twenty.envFromConfigMapName }}
            {{- end }}
            {{- if .Values.twenty.envFromSecretName }}
            - secretRef:
                name: {{ .Values.twenty.envFromSecretName }}
            {{- end }}
          {{- end -}}
          env:
            - name: NODE_PORT
              value: {{ .Values.twenty.port | quote }}
            {{- if .Values.postgresql.enabled }}
            - name: PG_DATABASE_URL
              value: "postgres://postgres:${PG_DATABASE_PASSWORD}@${PG_DATABASE_HOST}:${PG_DATABASE_PORT}/postgres"
            - name: PG_DATABASE_HOST
              value: {{ .Release.Name }}-postgresql
            - name: PG_DATABASE_PORT
              {{- if and .Values.postgresql.service .Values.postgresql.service.ports .Values.postgresql.service.ports.postgresql }}
              value: {{ include "postgresql.v1.primary.fullname" . }}
              {{- else }}
              value: "5432"
              {{- end }}
            - name: PG_DATABASE_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: {{ .Release.Name }}-postgresql
                  key: postgresql-password
            {{- end }}
            {{- if .Values.redis.enabled }}
            - name: REDIS_URL
              value: "redis://{{ .Release.Name }}-redis-master:6379"
            {{- end }}
          {{- include "twenty.renderEnvValues" . | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.twenty.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
