apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "twenty.fullname" . }}-worker
  labels:
    {{- include "twenty.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "twenty.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "twenty.labels" . | nindent 8 }}
        app.kubernetes.io/component: worker
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "twenty.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      - name: check-db-ready
        image: docker.io/bitnami/postgresql:17.4.0-debian-12-r11
        command: ['sh', '-c',
          'until pg_isready -U postgres -h {{ .Release.Name }}-postgresql -p 5432; 
          do echo waiting for database; sleep 2; done;']
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default ( printf "v%s" .Chart.AppVersion ) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ['yarn', 'worker:prod']
          {{- include "twenty.envBlock" ( set . "isWorker" "true" ) | indent 10 }}
          ports:
            - name: http
              containerPort: {{ .Values.twenty.port }}
              protocol: TCP
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}